Replace echo with printf, fix formatting

diff --git a/audio/cue-splitter b/audio/cue-splitter
--- a/audio/cue-splitter
+++ b/audio/cue-splitter
@@ -1,66 +1,66 @@
 #!/bin/bash
 
 # DESCRIPTION
-#     Splits FLAC, APE or WV using CUE sheet. 
-#     If the file is not FLAC, it also converts it to FLAC. The script also
-#     copies ID3v2 metadata from CUE sheet to each audio file.
+#   Splits FLAC, APE or WV using CUE sheet. 
+#   If the file is not FLAC, it also converts it to FLAC. The script also
+#   copies ID3v2 metadata from CUE sheet to each audio file.
 #
 # SYNTAX 
-#     - to split audio file using CUE sheet: 
-#       <FLAC filename or full path> <CUE filename or full path>
-#     - example: ./script Pete Namlook & Dr. Atmo ‎– Silence.flac \
-#                         Pete Namlook & Dr. Atmo ‎– Silence.cue
+#   - to split audio file using CUE sheet: 
+#     <FLAC filename or full path> <CUE filename or full path>
+#   - example: ./script Pete Namlook & Dr. Atmo ‎– Silence.flac \
+#                       Pete Namlook & Dr. Atmo ‎– Silence.cue
 #
 # NOTES
-#     - concerning the subject of quality loss while ecoding/decoding
-#       https://superuser.com/questions/447338/understanding-conversion-and-decompression-of-lossless-audio
-
-set -euo pipefail
+#   - concerning the subject of quality loss while ecoding/decoding
+#     https://superuser.com/questions/447338/understanding-conversion-and-decompression-of-lossless-audio
 
 check_dependencies () {
   dependencies=( "ffmpeg" "iconv" "shnsplit" "flac" "cuetag" )
 
-  for i in "${dependencies[@]}"; do
-    if ! command -v "$i" &> /dev/null
+  for dependency in "${dependencies[@]}"
+  do
+    if ! command -v "$dependency" &> /dev/null
     then 
-      echo "${i} required" && exit 1
+      printf "\n%s required.\n" "$dependency"
+      exit 1
     fi
   done
 }
 
 split_flac () {
-  echo -e "\n*** Split FLAC ***"
+  printf "\n*** Split FLAC ***\n"
 
-  echo -e "\n- Split audio file using CUE sheet"
-  echo "$AUDIO_NAME.flac"
+  printf "\n- Split audio file using CUE sheet\n"
+  printf "%s.flac\n" "$AUDIO_NAME"
   shnsplit \
     -f "$CUE_PATH" \
     -t "%n. %p - %t" \
     -o flac \
     "$AUDIO_NAME.flac"
   
-  echo -e "\n- Copy ID3v2 tags from CUE sheet to each audio file"
+  printf "\n- Copy ID3v2 tags from CUE sheet to each audio file\n"
   cuetag "$CUE_PATH" [[:digit:]]*.flac
 }
 
 convert_to_flac () {
-  echo -e "\n*** Convert source audio to FLAC ***"
+  printf "\n*** Convert source audio to FLAC ***\n"
 
   # `shnsplit` can convert APE to FLAC directly, but that requires us to 
   # install extra package - APE codec 
   # (https://github.com/fernandotcl/monkeys-audio). 
   # So instead of using `shnsplit` at this step I just use `ffmpeg` and `flac`.
 
-  echo -e "\n- Convert to WAV"
+  printf "\n- Convert to WAV\n"
   ffmpeg \
     -hide_banner \
     -loglevel error \
     -i "$AUDIO_BASENAME" "$AUDIO_NAME.wav"
 
-  echo -e "\n- Convert WAV to FLAC"
+  printf "\n- Convert WAV to FLAC\n"
   flac ./*.wav
 
-  echo -e "\n- Delete intermediate WAV file"
+  printf "\n- Delete intermediate WAV file\n"
   rm --verbose "$AUDIO_NAME.wav"
 }
 
@@ -72,22 +72,25 @@ process_audio () {
     "wv" | "ape" )
       convert_to_flac
       split_flac
-      echo -e "\n- Delete intermediate FLAC file"
+      printf "\n- Delete intermediate FLAC file\n"
       rm --verbose "$AUDIO_NAME.flac"
       ;;
     * )
-      echo -e "\nUnsupported audio format :(" && exit 1
+      printf "\nUnsupported audio format :(\n"
+      exit 1
   esac
 
   read -rp $'\nDo you want to delete _source_ file? [Yy/Nn] '
-  if [[ $REPLY =~ ^[Yy]$ ]]; then
+  if [[ $REPLY =~ ^[Yy]$ ]]
+  then
     rm --verbose "$AUDIO_BASENAME"
   fi
 
   echo -e "\nDone!"
 }
 
-
+set -eu -o pipefail
+clear
 
 check_dependencies
 
