Replace double with single quotes and echo with printf

diff --git a/webdev/npm-startapp b/webdev/npm-startapp
--- a/webdev/npm-startapp
+++ b/webdev/npm-startapp
@@ -1,28 +1,24 @@
 #!/bin/bash
 
-set -euo pipefail
+set -eu -o pipefail
 
-echo -e "\n##\n##\tRUNNING WITH ENVIRONMENT=\"${NODE_ENV}\"\n##\n\n"
+printf '\n##\n##\tRUNNING WITH ENVIRONMENT=\"%s\"\n##\n\n' "$NODE_ENV"
 
-#
-#
-# 
+printf 'Start app...\n'
 
-echo -e "Start app...\n"
-
-if [ "${NODE_ENV}" == "test" ]
+if [[ "${NODE_ENV}" == 'test' ]]
 then
 	npm run serve:test
 fi
 
-if [ "${NODE_ENV}" == "development" ]
+if [[ "${NODE_ENV}" == 'development' ]]
 then
   npm run serve:dev
 fi
 
-if [ "${NODE_ENV}" == "production" ]
+if [[ "${NODE_ENV}" == 'production' ]]
 then
 	npm run build
 else
-  echo -ne "Invalid argument. Allowed values are: 'dev', 'test', 'prod'\n\n"
+  printf 'Invalid argument. Allowed values are: "dev", "test", "prod"\n\n'
 fi
